input.onButtonPressed(Button.A, function () {
    for (let index = 0; index < 50; index++) {
        strip.showColor(neopixel.colors(NeoPixelColors.Red))
        basic.pause(200)
        strip.showColor(neopixel.colors(NeoPixelColors.Yellow))
        basic.pause(200)
        strip.showColor(neopixel.colors(NeoPixelColors.Green))
        basic.pause(200)
        strip.showColor(neopixel.colors(NeoPixelColors.Blue))
        basic.pause(200)
        strip.showColor(neopixel.colors(NeoPixelColors.Indigo))
        basic.pause(200)
        strip.showColor(neopixel.colors(NeoPixelColors.Violet))
        basic.pause(200)
        strip.showColor(neopixel.colors(NeoPixelColors.White))
        basic.pause(100)
        strip.showColor(neopixel.colors(NeoPixelColors.Purple))
        basic.pause(200)
        strip.showColor(neopixel.colors(NeoPixelColors.Orange))
    }
})
input.onButtonPressed(Button.B, function () {
    for (let index = 0; index < 50; index++) {
        strip.showColor(neopixel.colors(NeoPixelColors.Red))
        basic.pause(200)
        strip.showColor(neopixel.colors(NeoPixelColors.Yellow))
        basic.pause(200)
        strip.showColor(neopixel.colors(NeoPixelColors.Green))
        basic.pause(100)
        strip.showColor(neopixel.colors(NeoPixelColors.Blue))
        basic.pause(100)
        strip.showColor(neopixel.colors(NeoPixelColors.Indigo))
        basic.pause(500)
        strip.showColor(neopixel.colors(NeoPixelColors.Violet))
        basic.pause(100)
        strip.showColor(neopixel.colors(NeoPixelColors.White))
        basic.pause(200)
        strip.showColor(neopixel.colors(NeoPixelColors.Purple))
        basic.pause(500)
        strip.showColor(neopixel.colors(NeoPixelColors.Orange))
        basic.pause(100)
    }
})
let strip: neopixel.Strip = null
strip = neopixel.create(DigitalPin.P0, 13, NeoPixelMode.RGB)
strip.setBrightness(100)
basic.forever(function () {
    music.setBuiltInSpeakerEnabled(true)
})
